sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

install: composer self-update && composer install

script:
  - ./bin/phing run-tests
  - ./bin/phing phpmd

# Send coverage from Travis to Scrutnizer only if run from PHP 5.5
after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = 5.5 ]; then ./bin/phing coverage-clover; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = 5.5 ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = 5.5 ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
